✨ Feat: [프로그래머스][level 0] 023 - 024
f-lab-edu/study-fe-devoil pull request #10
Opened 2024-11-19 09:39 UTC by dev-oil

- [주사위 게임 2](https://school.programmers.co.kr/learn/courses/30/lessons/181930)
- [원소들의 합](https://school.programmers.co.kr/learn/courses/30/lessons/181929)

프로그래머스 코드리뷰 요청드립니다. 감사합니다.

2024-11-19 13:31 UTC, f-lab-jake requested changes

2024-11-19 13:31 UTC, f-lab-jake commented on ts-programmers/level0/023_주사위_게임_2.ts
> +    return (a + b + c) * (a**2 + b**2 + c**2);
중복을 줄이세요

2024-11-19 13:31 UTC, f-lab-jake commented on ts-programmers/level0/024_원소들의_곱과_합.ts
> +  }
for of을 사용하세요.

2024-11-21 05:30 UTC, bglgwyng approved these changes
ts-programmers/level0/023_주사위_게임_2.ts

요거는 제가 생각했던 개선안이 딱히 별로 좋은거같지가 않네요.
고친거나 원래거나 또이또이입니다. 일단 지나갑시다.

2024-11-21 05:34 UTC, merged