✨ Feat: [프로그래머스][level 0] 034 - 038
f-lab-edu/study-fe-devoil pull request #19
Opened 2024-12-04 12:33 UTC by dev-oil

### 문제 링크
[콜라츠 수열 만들기](https://school.programmers.co.kr/learn/courses/30/lessons/181919)
[배열 만들기 4](https://school.programmers.co.kr/learn/courses/30/lessons/181918)
[간단한 논리 연산](https://school.programmers.co.kr/learn/courses/30/lessons/181917)
[주사위 게임 3](https://school.programmers.co.kr/learn/courses/30/lessons/181916)
[글자 이어 붙여 문자열 만들기](https://school.programmers.co.kr/learn/courses/30/lessons/181915)

프로그래머스 코드리뷰 요청드립니다. 감사합니다.

2024-12-06 14:56 UTC, f-lab-jake requested changes

2024-12-06 14:56 UTC, f-lab-jake commented on ts-programmers/level0/034_콜라츠_수열_만들기.ts
> +  answer.push(n);
`push`를 한번만 쓰세요

2024-12-06 14:56 UTC, f-lab-jake commented on ts-programmers/level0/035_배열_만들기_4.ts
> +    } else {
중복을 제거하세요

2024-12-06 14:56 UTC, f-lab-jake commented on ts-programmers/level0/037_주사위_게임_3.ts
> +}
정렬을 써보세요

2025-01-02 07:31 UTC, dev-oil commented on ts-programmers/level0/035_배열_만들기_4.ts
> +    } else {
@f-lab-jake  2번 풀이에 중복 제거한 버전 올려두었습니다!

2025-01-04 03:12 UTC, f-lab-jake requested changes

2025-01-04 03:12 UTC, f-lab-jake commented on ts-programmers/level0/034_콜라츠_수열_만들기.ts
>  }
새로운 배열을 리턴해보세요. 배열을 인자로 받아서 push하는 대신에요.

2025-01-06 09:08 UTC, f-lab-jake reviewed
별로 효율적으로 보이진않죠? 멘토링 시간에 마저 이야기합시다.

2025-01-14 06:36 UTC, merged