✨ Feat: 2주차 숙제
f-lab-edu/study-fe-devoil pull request #9
Opened 2024-11-14 09:42 UTC by dev-oil

### 개요
- 멘토링 2주차 때 말씀 주셨던 숙제 PR 전달드립니다.
- 감사합니다!

### 내역
1. 프로그래머스 코드처리하기 솔루션 함수 수정
2. map 함수 구현하기
3. setInterval setTimeout으로 구현하기

2024-11-14 12:46 UTC, f-lab-jake requested changes

2024-11-14 12:46 UTC, f-lab-jake commented on mentoring/2week_homework.ts
> +  for (let i = 0; i < code.length; i++) {
`code.entries()`쓰세요

2024-11-14 12:46 UTC, f-lab-jake commented on mentoring/2week_homework.ts
> +      }
중복을 개선하세요

2024-11-21 05:30 UTC, bglgwyng approved these changes

2024-11-21 05:32 UTC, merged